# Generated by Django 4.1.4 on 2022-12-29 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='coursecode',
            field=models.ForeignKey(default='DCS', on_delete=django.db.models.deletion.CASCADE, to='registration.course'),
        ),
    ]
