# Generated by Django 4.1.4 on 2022-12-29 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_alter_student_coursecode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='studentid',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
